package ws_server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-28T16:51:53.639+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://ws_server/", name = "WsInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WsInterface {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws_server/", className = "ws_server.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws_server/", className = "ws_server.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws_server/", className = "ws_server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws_server/", className = "ws_server.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
